In [1]:
#Esta línea se utiliza para que las gráficas que se creen queden embebidas dentro de la notebook.
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
#Los comentatios en Pytho empiezan con el signo #
#Cargar módulo de numpy
import numpy as np

In [3]:
vector = array([1,2,3,4,5,6])
matriz = array([[1, 2], [3, 4], [5, 6]])

In [4]:
#imprimir contenido y tamaño del vector y la matriz
print(vector)
print()  #Línea vacía
print(matriz)
print()
print("Tamaño del vector {}".format(vector.shape))
print("Tamaño de la matriz {}".format(matriz.shape))

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

Tamaño del vector (6,)
Tamaño de la matriz (3, 2)


In [5]:
#Los valores del tamaño del vector o matrices se pueden acceder de la siguiente manera

v_elem = vector.size

#Forma 1
m_reng, m_column = matriz.shape

#Forma 2
m_reng = matriz.shape[0]
m_column = matriz.shape[1]

#Forma 3
m_reng, m_column = matriz.shape[0], matriz.shape[1]


print("El vector tiene {} elementos".format(v_elem))
print("La matriz es de {},{} con un total de {} elementos".format(m_reng, m_column, matriz.size))

El vector tiene 6 elementos
La matriz es de 3,2 con un total de 6 elementos


In [6]:
#También se pueden crear vectores y matrices de la siguiente forma
v_ceros = zeros(4)
v_unos = ones(4)
v_random = np.random.rand(8)    #Se generan números aleatorios

m_ceros = zeros([4,3])
m_unos = ones([4,5])
m_random = np.random.rand(6,4) #Se generan números aleatorios

In [7]:
print("Imprimiendo los vectores")
print(v_ceros)
print(v_unos)
print(v_random)
print()
print("Imprimiendo las matrices")
print(m_ceros)
print(m_unos)
print(m_random)

Imprimiendo los vectores
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[0.0839523  0.25867127 0.39998623 0.74687746 0.71300165 0.32058521
 0.60456517 0.9595909 ]

Imprimiendo las matrices
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.78196686 0.16028104 0.32311857 0.3481049 ]
 [0.12943868 0.44681751 0.90365473 0.90851129]
 [0.53828863 0.00623149 0.9594307  0.23800294]
 [0.3424464  0.60746972 0.48736512 0.0922825 ]
 [0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]


In [8]:
# Los índices de los vectores y matrices empiezan en cero
print(v_random[1])
print(v_random[3]) #El índice 3 no existe, por lo que marca un error al tratar de acceder a él

0.258671268876704
0.7468774573304133


In [9]:
#Los índices de las matrices están organizados de la forma [renglones, columnas]
print("Renglo 1 {}".format(m_random[1,:]))

Renglo 1 [0.12943868 0.44681751 0.90365473 0.90851129]


In [10]:
print("Columna 3 {}".format(m_random[:,3]))

Columna 3 [0.3481049  0.90851129 0.23800294 0.0922825  0.61399671 0.42750015]


In [11]:
print("Primero dos renglones {}".format(m_random[:2]))

Primero dos renglones [[0.78196686 0.16028104 0.32311857 0.3481049 ]
 [0.12943868 0.44681751 0.90365473 0.90851129]]


In [12]:
print("Del renglón 3 en adelante {}".format(m_random[3:]))

Del renglón 3 en adelante [[0.3424464  0.60746972 0.48736512 0.0922825 ]
 [0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]


In [13]:
print("Últimos dos renglones {}".format(m_random[-2:]))

Últimos dos renglones [[0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]


In [14]:
print("Últimos dos renglones {}".format(m_random[,-2:]))

SyntaxError: invalid syntax (<ipython-input-14-9ae9467d4c3d>, line 1)

In [15]:
print("Original: {}".format(v_random))
#Se hace un sub-vector de 3 elementos empezando por el que está en el índice 3 y hasta el 5. 
#Como se observa, el primer índice la posición del primer elemento que se va a tomar, mientras que el segundo 
#índice indica que se va a tomar hasta el elemento anterior a ese índice.

sub_v = v_random[3:6]
print("sub_1 del 3-5: {}".format(sub_v))

sub_v2 = v_random[5:9]
print("sub_2: del 5-8 {}".format(sub_v2))

Original: [0.0839523  0.25867127 0.39998623 0.74687746 0.71300165 0.32058521
 0.60456517 0.9595909 ]
sub_1 del 3-5: [0.74687746 0.71300165 0.32058521]
sub_2: del 5-8 [0.32058521 0.60456517 0.9595909 ]


In [16]:
print("Original")
print(m_random)
print("\n Sub-conjunto [1-2-3, 1-2]")
print(m_random[1:4,1:3])

Original
[[0.78196686 0.16028104 0.32311857 0.3481049 ]
 [0.12943868 0.44681751 0.90365473 0.90851129]
 [0.53828863 0.00623149 0.9594307  0.23800294]
 [0.3424464  0.60746972 0.48736512 0.0922825 ]
 [0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]

 Sub-conjunto [1-2-3, 1-2]
[[0.44681751 0.90365473]
 [0.00623149 0.9594307 ]
 [0.60746972 0.48736512]]


In [17]:
#Los arreglos y vectores también se pueden recorrer mediante ciclos
#Recorriendo la matriz usando índices
for i in range(0, m_random.shape[0]):
    print(m_random[i,:]) #Se imprime el renlón completo
    for j in range(0, m_random.shape[1]):
        print(m_random[i,j]) #Se imprime el elemento de cada renglón

[0.78196686 0.16028104 0.32311857 0.3481049 ]
0.7819668593209975
0.16028104091992368
0.32311857099905406
0.3481048977341522
[0.12943868 0.44681751 0.90365473 0.90851129]
0.12943867644163354
0.446817507383531
0.9036547305344922
0.9085112865238631
[0.53828863 0.00623149 0.9594307  0.23800294]
0.5382886289789685
0.006231490853165211
0.9594306956777989
0.2380029406464701
[0.3424464  0.60746972 0.48736512 0.0922825 ]
0.3424463972903731
0.607469719801249
0.48736511620754075
0.09228249888142748
[0.69219939 0.63418982 0.76200462 0.61399671]
0.6921993890515798
0.6341898192602069
0.7620046216500574
0.6139967128489077
[0.96294278 0.92767865 0.94388236 0.42750015]
0.9629427762805857
0.9276786498577272
0.9438823598022311
0.42750015473138836


In [18]:
print("Original:")
print(m_random)

Original:
[[0.78196686 0.16028104 0.32311857 0.3481049 ]
 [0.12943868 0.44681751 0.90365473 0.90851129]
 [0.53828863 0.00623149 0.9594307  0.23800294]
 [0.3424464  0.60746972 0.48736512 0.0922825 ]
 [0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]


In [19]:
#Guardando la matriz m_random en el archivo m_random.csv usando como delimitador ','
np.savetxt("m_random.csv",m_random, delimiter=",")

In [21]:
#Cargando la matriz guardada en m_random.csv
m_load = np.loadtxt("m_random.csv",delimiter=",")

In [22]:
print("Matriz guardada y cargada:")
print(m_load)

Matriz guardada y cargada:
[[0.78196686 0.16028104 0.32311857 0.3481049 ]
 [0.12943868 0.44681751 0.90365473 0.90851129]
 [0.53828863 0.00623149 0.9594307  0.23800294]
 [0.3424464  0.60746972 0.48736512 0.0922825 ]
 [0.69219939 0.63418982 0.76200462 0.61399671]
 [0.96294278 0.92767865 0.94388236 0.42750015]]


In [23]:
#Simplemente se multiplica la matriz por el escalar deseado
resultado = m_unos * 9
print(resultado)

[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]]


In [24]:
#Para hacer la transpuesta de una matriz, sólo se utiliza el operador T a la matriz
result_T = resultado.T
print(result_T)

[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [25]:
#Para la multiplicación de matrices se necesitas que el índice las columnas de la primera matriz coincida 
#con el índice de renglones de la segunda matriz
print("Índices de las matrices:")
print(m_unos.shape)
print(result_T.shape)

#Para realizar la operación se utiliza la función dot()
print("\nResultado de la multiplicación m_unos * result_T")
print(np.dot(m_unos, result_T))

Índices de las matrices:
(4, 5)
(5, 4)

Resultado de la multiplicación m_unos * result_T
[[45. 45. 45. 45.]
 [45. 45. 45. 45.]
 [45. 45. 45. 45.]
 [45. 45. 45. 45.]]
